# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e3ff0a8d2eedf3ae026857efe263803d82aefe33917867a9634ef71935797f44c580af9677b0a3cdc46463b16e4ec9cb19a797c73934842e9e0855c20d4ec9a

test:
  secret_key_base: c1c128afe9e5edfffae998b220e390ddbd8eda279903eb6f7641192e9a59394f6b6f34192565b74e38bc0fad2c2e314b472375a8eb98c09691527247bba6547c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
